// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC48mj_gIuXREjUZVW97rzkKrAhYgpB64I',
    appId: '1:166835232707:web:6fbf497a76d25bea1d6776',
    messagingSenderId: '166835232707',
    projectId: 'registration-a077a',
    authDomain: 'registration-a077a.firebaseapp.com',
    storageBucket: 'registration-a077a.firebasestorage.app',
    measurementId: 'G-MRKPFZP4FP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNS2re3SwWwJcoal0ERBIKHLP2STfxp8g',
    appId: '1:166835232707:android:f90168ceacf9b5371d6776',
    messagingSenderId: '166835232707',
    projectId: 'registration-a077a',
    storageBucket: 'registration-a077a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk3wm7WS1-U8UnG7XoxtnBi6LBJr1-uIc',
    appId: '1:166835232707:ios:ccecc30e87d0caab1d6776',
    messagingSenderId: '166835232707',
    projectId: 'registration-a077a',
    storageBucket: 'registration-a077a.firebasestorage.app',
    iosBundleId: 'com.example.registrationAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk3wm7WS1-U8UnG7XoxtnBi6LBJr1-uIc',
    appId: '1:166835232707:ios:ccecc30e87d0caab1d6776',
    messagingSenderId: '166835232707',
    projectId: 'registration-a077a',
    storageBucket: 'registration-a077a.firebasestorage.app',
    iosBundleId: 'com.example.registrationAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC48mj_gIuXREjUZVW97rzkKrAhYgpB64I',
    appId: '1:166835232707:web:69db35fe269554821d6776',
    messagingSenderId: '166835232707',
    projectId: 'registration-a077a',
    authDomain: 'registration-a077a.firebaseapp.com',
    storageBucket: 'registration-a077a.firebasestorage.app',
    measurementId: 'G-KERV7HYHKQ',
  );
}
